GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/6a502bbd4d333e7d8c86d26d

###

PUT http://localhost:3001/api/notes/6a507417029b4ae83a801f35
Content-Type: application/json

{
  "content": "JavaScript is the best",
  "important": false
}

###

DELETE http://localhost:3001/api/notes/6a502bbd4d333e7d8c86d26e

###

POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2YTU3MTdmNDQ2YjYzYjI1M2UwYTNhNGIiLCJpYXQiOjE3ODQzMDkzNjl9.FB24NZsOAsGbLMuU6EherHS0jWeGYed8nU5oH1AXFXc

{
  "content": "Single page apps use token based auth",
  "important": true
}
