GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/6a502bbd4d333e7d8c86d26d

###

PUT http://localhost:3001/api/notes/6a507417029b4ae83a801f35
content-type: application/json

{
  "content": "JavaScript is the best",
  "important": false
}

###

DELETE http://localhost:3001/api/notes/6a502bbd4d333e7d8c86d26e

###

POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
  "content": "The existing code and tests need to be changed when user is added to system",
  "important": true,
  "userId": "6a57177f46b63b253e0a3a4a"
}
