GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/1

###

DELETE http://localhost:3001/api/notes/6a5078cadfcaa4b316598885

###

POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "JavaScript is the best",
    "important": false
}
