GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Bob's Dumpy Blog",
  "author": "Bob McBob",
  "url": "https://bobdumpyblog.com",
  "likes": 0,
  "user": "6a5ac26575bf51ab130d0c7e"
}
