GET https://phonebook-backend-nu.vercel.app/api/persons

###

GET https://phonebook-backend-nu.vercel.app/api/persons/4

###

DELETE https://phonebook-backend-nu.vercel.app/api/persons/2

###

POST https://phonebook-backend-nu.vercel.app/api/persons
Content-Type: application/json

{
  "name": "Andrew Lee",
  "number": "1-312-282-6693"
}
