GET https://phonebook-backend-nu.vercel.app/api/persons

###

GET https://phonebook-backend-nu.vercel.app/api/persons/6a506650127bedacbdfc7d70

###

PUT https://phonebook-backend-nu.vercel.app/api/persons/6a518373edd6e257e21659d4
Content-Type: application/json

{
  "name": "Andrew Lee",
  "number": "999"
}

###

DELETE https://phonebook-backend-nu.vercel.app/api/persons/6a5097aafb657e012b6eee59

###

POST https://phonebook-backend-nu.vercel.app/api/persons
Content-Type: application/json

{
  "name": "Andrew Lee",
  "number": "1-312-282-6693"
}
