GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/4

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Andrew Lee",
  "number": "1-312-282-6693"
}
